<?php

namespace Home\HomeBundle\Entity;

/**
 * bodyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bodyRepository extends \Doctrine\ORM\EntityRepository
{
}
