advertisement:
    resource: "@AdvertisementBundle/Resources/config/routing.yml"
    prefix:   /Annonce

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"