<?php

namespace Administration\AdminBundle\Entity\Repository;

/**
 * HomesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomesKindRepository extends \Doctrine\ORM\EntityRepository
{
}
