<?php

namespace Administration\AdminBundle\Entity\Repository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Method to get Subcategory with Category
	 *
	 * @return array
	 */
	public function getSubcategoriesWithCategories()
	{
		$qb = $this->createQueryBuilder('sc')
				->leftJoin('sc.Category', 'c')
				->select('sc, c')
				->orderBy('sc.name');

		return $qb->getQuery()->getResult();
	}
}
