<?php

namespace Home\HomeBundle\Entity\Repository;

/**
 * bodyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BodyRepository extends \Doctrine\ORM\EntityRepository
{
}
