home_car:
    resource: "@AdvertisementBundle/Resources/config/routing/car.yml"
    prefix:   /car

advertisement_homepage:
    path:     /
    defaults: { _controller: 'AdvertisementBundle:Default:index' }

ViewAdvertisement:
    path:     /Creation
    defaults: { _controller: 'AdvertisementBundle:Advertisement:ViewAdvertisement' }

RouterAdvertisement:
    path:     /router/{id}
    defaults: { _controller: 'AdvertisementBundle:Advertisement:RouterFunctionByEntities' }
    methods:  [GET, POST]

GetSubcategoriesById:
    path:     /GetSubcategoriesById/{id}
    defaults: { _controller: 'AdvertisementBundle:Advertisement:GetSubcategoriesById' }
    options:
        expose: true

ajax:
    path: /ajax
    defaults: { _controller : 'AdvertisementBundle:Car:new' }
    options:
        expose: true