home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

NewAdvertisement:
    path:     /NewAdvertisement
    defaults: { _controller: HomeBundle:Advertisement:NewAdvertisement }

GetSubcategories:
    path:     /GetSubcategories/{id}
    defaults: { _controller: HomeBundle:Advertisement:GetSubcategories }
    options:
        expose: true