<?php

namespace Advertisement\AdvertisementBundle\Repository;

/**
 * AdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Method to get Adverts with files
	 *
	 * @return array
	 */
	public function getAdvertsWithFile()
	{
		$qb = $this->createQueryBuilder('a')
			->leftJoin('a.mediaFirst', 'm')
			->select('a, m')
			->orderBy('a.dateAdd', 'DESC');

		return $qb->getQuery()->getResult();
	}
}
