<?php

namespace Advertisement\AdvertisementBundle\Repository;

/**
 * AdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Method to get Adverts with files
	 *
	 * @return array
	 */
	public function getAdvertsWithFile()
	{
		$qb = $this->createQueryBuilder('a')
			->leftJoin('a.mediaFirst', 'm')
			->select('a, m')
			->orderBy('a.dateAdd', 'DESC');

		return $qb->getQuery()->getResult();
	}

	/**
	 * Method to get Advert with files
	 *
	 * @param $id
	 * @return array
	 */
	public function getAdvertWithFile($id)
	{
		$qb = $this->createQueryBuilder('a')
			->leftJoin('a.mediaFirst', 'm')
			->leftJoin('a.ObjectToSell', 'o')
			->select('a, o, m')
			->where('a.id = :id')
			->orderBy('a.dateAdd', 'DESC')
			->setParameter('id', $id);

		return $qb->getQuery()->getResult();
	}

	/**
	 * Methode to get Advert where query parameters
	 * @param $query
	 */
	public function getAdvertWithWhere($query)
	{
		$qb = $this->createQueryBuilder('a')
			->leftJoin('a.mediaFirst', 'm')
			->select('a, m')
			->where('a.title like :query')
			->orWhere('a.description like :query')
			->orderBy('a.dateAdd', 'DESC')
			->setParameter('query', '%' . $query . '%');
		;

		return $qb->getQuery()->getResult();

	}
}
