<?php

namespace Advertisement\AdvertisementBundle\Repository;

/**
 * HomesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomesRepository extends \Doctrine\ORM\EntityRepository
{
}
