<?php

namespace Advertisement\AdvertisementBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ObjectToSellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectToSellRepository extends EntityRepository
{
}
