<?php

namespace Advertisement\AdvertisementBundle\Repository;

/**
 * PetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetsRepository extends \Doctrine\ORM\EntityRepository
{
}
